name: Build

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - multiarch-build
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.repository_owner == 'hawtio'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build
        run: |
          mvn --batch-mode --no-transfer-progress install
