name: Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.repository_owner == 'hawtio'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build and push image to Quay.io
        if: github.event_name == 'push'
        env:
          USERNAME: ${{ secrets.QUAY_USERNAME }}
          PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          docker login --help
          docker login -u $USERNAME -p $PASSWORD quay.io

          mvn --batch-mode --no-transfer-progress -pl '!camel-quarkus-openshift' install \
            -Dquarkus.jib.base-jvm-image=registry.access.redhat.com/ubi9/openjdk-${{ matrix.java }}-runtime:latest \
            -Dquarkus.jib.platforms=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
            -Dquarkus.container-image.name=hawtio-online-example-camel-quarkus \
            -Dquarkus.container-image.tag=${{ matrix.java }} \
            -Dquarkus.container-image.push=true \
            -Djkube.generator.from=registry.access.redhat.com/ubi9/openjdk-${{ matrix.java }}:latest \
            -Djkube.build.strategy=docker

          docker buildx build -t quay.io/hawtio/hawtio-online-example-camel-springboot:${{ matrix.java }} \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
            --provenance=false \
            --push \
            camel-springboot/target/docker/quay.io/hawtio/hawtio-online-example-camel-springboot/latest/build/

          if [[ "${{ matrix.java }}" == "21" ]]; then
            docker buildx imagetools create -t quay.io/hawtio/hawtio-online-example-camel-quarkus:latest quay.io/hawtio/hawtio-online-example-camel-quarkus:${{ matrix.java }}
            docker buildx imagetools create -t quay.io/hawtio/hawtio-online-example-camel-springboot:latest quay.io/hawtio/hawtio-online-example-camel-springboot:${{ matrix.java }}
          fi
